### ISSUE TITLE
Can't install this package in Laravel 5.3

### ISSUE THREAD

**Issue by shabaz-ejaz** [achillesp/laravel-crud-forms#1]
I get the following error when trying to install the package through composer:

```
Problem 1
    - Installation request for achillesp/laravel-crud-forms ^1.1 -> satisfiable by achillesp/laravel-crud-forms[1.1].
    - Conclusion: remove laravel/framework v5.3.31
    - Conclusion: don't install laravel/framework v5.3.31
    - achillesp/laravel-crud-forms 1.1 requires illuminate/http ^5.5 -> satisfiable by illuminate/http[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/http v5.5.0|don't install laravel/framework v5.3.31
    - don't install illuminate/http v5.5.16|don't install laravel/framework v5.3.31
    - don't install illuminate/http v5.5.17|don't install laravel/framework v5.3.31
    - don't install illuminate/http v5.5.2|don't install laravel/framework v5.3.31
    - Installation request for laravel/framework (locked at v5.3.31, required as 5.3.*) -> satisfiable by laravel/framework[v5.3.31].
```

**Comment by achillesp** [comment]
Sorry, only Laravel >= 5.5 is supported at the moment.

**Comment by shabaz-ejaz** [comment]
That's a shame!

**Comment by staudacher** [comment]
That's not a shame, that's a decision you apparently have to accept.

**Comment by shabaz-ejaz** [comment]
It is a shame, the README file states the following 

> If using a Laravel version before 5.5, you will need to add the service provider to your app's providers array in config/app.php:

This made me assume 5.3 was supported. Maybe you should remove this to avoid confusion. 


Also the README file was [edited just a few hours ago](https://github.com/achillesp/laravel-crud-forms/commit/7fb2a4fa442cc9c662c2e34ab70e33eef9ceb6b2#diff-0730bb7c2e8f9ea2438b52e419dd86c9) to state that this was for Laravel 5.5 onwards, so yeah it is a shame!

**Comment by patriziotomato** [comment]
If the readme now contains an important hint: Thanks for your feedback. Anyway, not need to get impolite, since you're still using something that someone has development for the community. You do not need to use it at all. 

https://en.wikipedia.org/wiki/Social

**Comment by shabaz-ejaz** [comment]
@patriziotomato Who was getting impolite? I was merely stating the fact that when I imported the package there was no mention of it only being compatible with L5.5 upwards. So this was added after. I think the impolite comment was from @staudacher. Maybe he's just having  a bad hair day.
