### ISSUE TITLE
Styles not showing in any views

### ISSUE THREAD

**Issue by doublehops** [achillesp/laravel-crud-forms#3]
I have installed `laravel-crud-forms` and followed the install steps but no styles are showing. No stylesheets are being included. Is there possibly a step that I missed?

Laravel 5.5

**Comment by achillesp** [comment]
Check the config file?

**Comment by doublehops** [comment]
Are you referring to the layout? I see that I can override that in the controller's constructor with `$this->bladeLayout = 'layouts.app'` but if I change that the CRUD views don't show at all. Maybe I'm a little lost in the blade aspect of things and not this library instead.

**Comment by achillesp** [comment]
The package also has a config file. To get it working correctly with default Laravel install, in the config set:
```php
'blade_layout' => 'layouts.app',
'blade_section' => 'content',
'button_icons' => 'false'
```
